//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.17929
//     Generated on:    21/05/2014 3:21:17 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace eHealth.DHPO.Schema.RemittanceAdvice {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("Remittance.Advice", Namespace="", IsNullable=false)]
    public partial class RemittanceAdvice {
        
        /// <remarks/>
        public RemittanceAdviceHeader Header;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Claim")]
        public RemittanceAdviceClaimCollection Claim;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RemittanceAdviceHeader {
        
        /// <remarks/>
        public string SenderID;
        
        /// <remarks/>
        public string ReceiverID;
        
        /// <remarks/>
        public string TransactionDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string RecordCount;
        
        /// <remarks/>
        public HeaderDispositionFlag DispositionFlag;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ValidationSchema")]
    public enum HeaderDispositionFlag {
        
        /// <remarks/>
        TEST,
        
        /// <remarks/>
        PRODUCTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RemittanceAdviceClaim {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string IDPayer;
        
        /// <remarks/>
        public string ProviderID;
        
        /// <remarks/>
        public string DenialCode;
        
        /// <remarks/>
        public string PaymentReference;
        
        /// <remarks/>
        public string DateSettlement;
        
        /// <remarks/>
        public RemittanceAdviceClaimEncounter Encounter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity")]
        public RemittanceAdviceClaimActivityCollection Activity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RemittanceAdviceClaimEncounter {
        
        /// <remarks/>
        public string FacilityID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RemittanceAdviceClaimActivity {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string Start;
        
        /// <remarks/>
        public ActivityType Type;
        
        /// <remarks/>
        public string Code;
        
        /// <remarks/>
        public float Quantity;
        
        /// <remarks/>
        public float Net;
        
        /// <remarks/>
        public float List;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListSpecified;
        
        /// <remarks/>
        public string Clinician;
        
        /// <remarks/>
        public string PriorAuthorizationID;
        
        /// <remarks/>
        public float Gross;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossSpecified;
        
        /// <remarks/>
        public float PatientShare;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientShareSpecified;
        
        /// <remarks/>
        public float PaymentAmount;
        
        /// <remarks/>
        public string DenialCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ValidationSchema")]
    public enum ActivityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,


        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class RemittanceAdviceClaimCollection : System.Collections.Generic.List<RemittanceAdviceClaim> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class RemittanceAdviceClaimActivityCollection : System.Collections.Generic.List<RemittanceAdviceClaimActivity> {
    }
}
#pragma warning restore 1591