//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by the XsdToClasses tool.
//     Tool Version:    1.2.23.0
//     Runtime Version: 4.0.30319.17929
//     Generated on:    03/06/2014 8:33:44 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
// Workaround for bug http://lab.msdn.microsoft.com/productfeedback/viewfeedback.aspx?feedbackid=d457a36e-0ce8-4368-9a27-92762860d8e1
#pragma warning disable 1591
namespace eHealth.DHPO.Schema.PriorAuthorization {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("Prior.Authorization", Namespace="", IsNullable=false)]
    public partial class PriorAuthorization {
        
        /// <remarks/>
        public PriorAuthorizationHeader Header;
        
        /// <remarks/>
        public PriorAuthorizationAuthorization Authorization;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PriorAuthorizationHeader {
        
        /// <remarks/>
        public string SenderID;
        
        /// <remarks/>
        public string ReceiverID;
        
        /// <remarks/>
        public string TransactionDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string RecordCount;
        
        /// <remarks/>
        public HeaderDispositionFlag DispositionFlag;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ValidationSchema")]
    public enum HeaderDispositionFlag {
        
        /// <remarks/>
        TEST,
        
        /// <remarks/>
        PRODUCTION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PriorAuthorizationAuthorization {
        
        /// <remarks/>
        public string Result;
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public string IDPayer;
        
        /// <remarks/>
        public string DenialCode;
        
        /// <remarks/>
        public string Start;
        
        /// <remarks/>
        public string End;
        
        /// <remarks/>
        public float Limit;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimitSpecified;
        
        /// <remarks/>
        public string Comments;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Activity")]
        public PriorAuthorizationAuthorizationActivityCollection Activity;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PriorAuthorizationAuthorizationActivity {
        
        /// <remarks/>
        public string ID;
        
        /// <remarks/>
        public ActivityType Type;
        
        /// <remarks/>
        public string Code;
        
        /// <remarks/>
        public float Quantity;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified;
        
        /// <remarks/>
        public float Net;
        
        /// <remarks/>
        public float List;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListSpecified;
        
        /// <remarks/>
        public float PatientShare;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PatientShareSpecified;
        
        /// <remarks/>
        public float PaymentAmount;
        
        /// <remarks/>
        public string DenialCode;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Observation")]
        public PriorAuthorizationAuthorizationActivityObservationCollection Observation;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ValidationSchema")]
    public enum ActivityType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class PriorAuthorizationAuthorizationActivityObservation {
        
        /// <remarks/>
        public ObservationType Type;
        
        /// <remarks/>
        public string Code;
        
        /// <remarks/>
        public string Value;
        
        /// <remarks/>
        public string ValueType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ValidationSchema")]
    public enum ObservationType {
        
        /// <remarks/>
        LOINC,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        File,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Universal Dental")]
        UniversalDental,
        
        /// <remarks/>
        Financial,
        
        /// <remarks/>
        Grouping,
        
        /// <remarks/>
        ERX,
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class PriorAuthorizationAuthorizationActivityCollection : System.Collections.Generic.List<PriorAuthorizationAuthorizationActivity> {
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace=null)]
    public partial class PriorAuthorizationAuthorizationActivityObservationCollection : System.Collections.Generic.List<PriorAuthorizationAuthorizationActivityObservation> {
    }
}
#pragma warning restore 1591